version: '3.4'

services:

  mc2db:
    container_name: mc2db
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  mc2.crudtest.presentation.server:
    container_name: customers.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Default=Server=mc2db;Database=MC2DB;User Id=sa;Password=SwN12345678"

      - ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on: 
      - mc2db
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
